### ISSUE TITLE
Find a smart way to pass the Giphy API Key to giphyserver

### ISSUE THREAD

**Issue by pyaillet** [pyaillet/etendre-k8s#3]

**Comment by ebriand** [comment]
In the controller deployment, we can reference it as an env variable : 
```yaml
containers:
        - name: giphy-operator
          env:
            - name: GIPHY_API_KEY
              value: $SECRET_API_KEY
```
